### ISSUE TITLE
Results?

### ISSUE THREAD

**Issue by bittlingmayer** [iamaziz/language-detection-fastText#1]
I tried something similar on a subset of [the Twitter dataset](https://blog.twitter.com/engineering/en_us/a/2015/evaluating-language-identification-performance.html).

How accurate was the result?

**Comment by iamaziz** [comment]
Cool! The test accuracy on the eval set was around 98.9% P@1 (Check it out [under cell 13](http://nbviewer.jupyter.org/github/iamaziz/language-detection-fastText/blob/master/demo.ipynb#3.-Training-classifier)).

UPDATE: 

I just added [another notebook](https://github.com/iamaziz/language-detection-fastText/blob/master/results.ipynb) for results on the test dataset.

**Comment by bittlingmayer** [comment]
As you probably heard, fastText has released their own lang id:

https://fasttext.cc/blog/2017/10/02/blog-post.html#fast-and-accurate-language-identification-using-fasttext
